- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch vm001
      os_server:
        image: 5f976278-67ca-4e6f-a1ca-59359f86c6be
        key_name: key
        name: vm001
        availability_zone: nova
        flavor: std.1
        state: present
        network: 901503af-1747-4e77-b6d1-ee38c3a65ec6