- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch vm002
      os_server:
        image: 79f64681-3525-4bbc-8149-917cd7cd050e
        key_name: key
        name: vm002
        availability_zone: nova
        flavor: std.1
        state: present
        network: 901503af-1747-4e77-b6d1-ee38c3a65ec6