- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch vm001
      os_server:
        image: 2529244a-85d5-4933-a754-b30b3a2d020f
        key_name: key
        name: vm001
        availability_zone: nova
        flavor: std.1
        state: present
        network: 901503af-1747-4e77-b6d1-ee38c3a65ec6