- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch vm012
      os_server:
        image: 5f976278-67ca-4e6f-a1ca-59359f86c6be
        name: vm012
        availability_zone: nova
        flavor: std.1
        state: present
        network: c05f9a1e-d998-4fd4-8afd-09ff52d4aa4d