- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch vm002
      os_server:
        image: 4c21cdb5-6aa2-4713-92b7-3b5139c372e3
        key_name: key
        name: vm002
        availability_zone: nova
        flavor: std.2
        state: present
        network: 901503af-1747-4e77-b6d1-ee38c3a65ec6