- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch CentOS7
      os_server:
        image: CentOS7
        name: test123
        availability_zone: nova
        flavor: std.1
        state: present
        network: LOCAL-NET
