- name: Launch a compute
  hosts: localhost
  tasks:
    - name: Launch Photon 3.0
      os_server:
        image: Photon 3.0
        name: vm005
        availability_zone: nova
        flavor: std.1
        state: present
        network: LOCAL-NET
